Allow writing mnemonics in ~A line
kinverarity1/lasio pull request #465
Opened 2021-05-15 09:58 UTC by kinverarity1

Partial implementation of #375 

Adds mnemonics_header and data_section_header to `writer.py:write`. The former is boolean controlling whether it occurs or not (off by default for backwards compatibility). The latter allows the prefix to be controlled e.g. "~A" vs "~ASCII".

The mnemonic headers are right-aligned based on the numeric value's column width, so that a fixed-width formatting parser can read it in. If the mnemonics are too long, then they are just placed one following the other, out of alignment.

See https://gist.github.com/kinverarity1/aaf3459c3fa3eeafe127c9011c15c835 for a demo.

2021-05-18 03:22 UTC, dcslagel requested changes
Looks good!  I've noted a few suggestions.

2021-05-19 15:13 UTC, dcslagel commented on lasio/writer.py
> +
Not a change request for this review but after this change merges, maybe look at moving the code that generates the `data_section_header` and `header_values` to a separate function.  The benefit is that then the main flow of the `if mnemonics_header:... else...` will be clearer.   However, there might variable scope issues that make moving the code complicated...

2021-06-10 21:57 UTC, dcslagel commented on lasio/writer.py
> +        mnemonics_header (bool): write mnemonics as header at top of data section
I put these suggestions on the dcslagel:data-header-line-optional-changes branch which can be closed or merged to this data-header-branch.  Either way, the  data-header-line pull-request can merge when you are ready.

2021-06-10 21:57 UTC, dcslagel commented on lasio/writer.py
> +        """Get left-hand-side spcaing for column *j*."""
I put these suggestions on the dcslagel:data-header-line-optional-changes branch which can be closed or merged to this data-header-branch.  Either way, the  data-header-line pull-request can merge when you are ready.

2021-06-10 21:57 UTC, dcslagel commented on lasio/writer.py
> +    def get_left_spacing(j):
I put these suggestions on the dcslagel:data-header-line-optional-changes branch which can be closed or merged to this data-header-branch.  Either way, the  data-header-line pull-request can merge when you are ready.

2021-06-10 21:57 UTC, dcslagel approved these changes
I put these suggestions on the dcslagel:data-header-line-optional-changes branch which can be closed or merged to this data-header-branch.  Either way, the  data-header-line pull-request can merge when you are ready.

2021-06-16 04:30 UTC, kinverarity1 commented
Thanks for the review and comments, and changes! 🎉 I will merge shortly.

2021-06-16 04:33 UTC, merged